complete -c kmonad-device-manager -s h -l help -d 'Show usage'
complete -c kmonad-device-manager -l json -d 'Emit machine-readable JSON'
complete -c kmonad-device-manager -l idempotency-key -r -d 'Reuse a durable mutation key'
complete -c kmonad-device-manager -l doctor -d 'Show a dependency status report'
complete -c kmonad-device-manager -l version -d 'Show version'
complete -c kmonad-device-manager -l status -d 'Show manager status'
complete -c kmonad-device-manager -l completion -r -a 'bash zsh fish' -d 'Print completion for a shell'
complete -c kmonad-device-manager -f -a ps -d 'Show manager status'
complete -c kmonad-device-manager -f -a devices -d 'List known keyboard devices'
complete -c kmonad-device-manager -f -a snapshot -d 'Read authoritative manager state'
complete -c kmonad-device-manager -f -a manager -d 'Read public manager metadata'
complete -c kmonad-device-manager -f -a events -d 'Stream manager state events'
complete -c kmonad-device-manager -f -a identify -d 'Run or inspect keyboard identification'
complete -c kmonad-device-manager -f -a inputscan -d 'Scan key capabilities or probe a named key'
complete -c kmonad-device-manager -f -a validate -d 'Preview a candidate without applying it'
complete -c kmonad-device-manager -f -a apply -d 'Transactionally persist and activate a managed configuration'
complete -c kmonad-device-manager -f -a config -d 'List or manage configurations'
complete -c kmonad-device-manager -n '__fish_seen_subcommand_from config' -f -a 'list read export create update enable disable delete adopt' -d 'Configuration action'
